services:
  yapi:
    build: ./
    container_name: yapi
    environment:
      - VERSION=1.12.0
      - ADMIN_EMAIL=admin@example.com # CHANGE ME, default password: ymfe.org
      - DB_SERVER=mongo
      - DB_PORT=27017
      - DB_NAME=yapi
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./log:/home/log
      - ./vendors:/home/vendors
    depends_on:
      mongo:
        condition: service_healthy
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
