allow-lan: true
mixed-port: 7899
bind-address: "*"
external-ui: "./ui"
external-controller: 0.0.0.0:9091
ipv6: false
log-level: info
mode: rule
dns:
  default-nameserver:
  - 223.5.5.5
  - 114.114.114.114
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - '*.lan'
  - '*.localdomain'
  - '*.example'
  - '*.invalid'
  - '*.localhost'
  - '*.test'
  - '*.local'
  - '*.home.arpa'
  - router.asus.com
  - localhost.sec.qq.com
  - localhost.ptlogin2.qq.com
  - +.msftconnecttest.com
  fake-ip-range: 198.18.0.1/16
  ipv6: false
  listen: 0.0.0.0:5352
  nameserver:
  - 223.5.5.5
  - 114.114.114.114
  - 119.29.29.29
  - 180.76.76.76
proxies:
proxy_groups:
rule-providers:
  Apple:
    behavior: classical
    path: ./rules/Apple.yaml
    type: http
    url: https://gcore.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Apple.list
  BanAD:
    behavior: classical
    path: ./rules/BanAD.yaml
    type: http
    url: https://gcore.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/BanAD.list
  BanProgramAD:
    behavior: classical
    path: ./rules/BanProgramAD.yaml
    type: http
    url: https://gcore.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/BanProgramAD.list
  ChinaCompanyIp:
    behavior: classical
    path: ./rules/ChinaCompanyIp.yaml
    type: http
    url: https://gcore.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaCompanyIp.list
  ChinaDomain:
    behavior: classical
    path: ./rules/ChinaDomain.yaml
    type: http
    url: https://gcore.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaDomain.list
  GoogleCN:
    behavior: classical
    path: ./rules/GoogleCN.yaml
    type: http
    url: https://gcore.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/GoogleCN.list
  LocalAreaNetwork:
    behavior: classical
    path: ./rules/LocalAreaNetwork.yaml
    type: http
    url: https://gcore.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/LocalAreaNetwork.list
  Microsoft:
    behavior: classical
    path: ./rules/Microsoft.yaml
    type: http
    url: https://gcore.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Microsoft.list
  ProxyLite:
    behavior: classical
    path: ./rules/ProxyLite.yaml
    type: http
    url: https://gcore.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ProxyLite.list
  ProxyMedia:
    behavior: classical
    path: ./rules/ProxyMedia.yaml
    type: http
    url: https://gcore.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ProxyMedia.list
  SteamCN:
    behavior: classical
    path: ./rules/SteamCN.yaml
    type: http
    url: https://gcore.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/SteamCN.list
  Telegram:
    behavior: classical
    path: ./rules/Telegram.yaml
    type: http
    url: https://gcore.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Telegram.list
rules:
  - RULE-SET,LocalAreaNetwork,DIRECT
  - RULE-SET,ChinaDomain,DIRECT
  - RULE-SET,ChinaCompanyIp,DIRECT
  - RULE-SET,GoogleCN,DIRECT
  - RULE-SET,SteamCN,DIRECT
  - RULE-SET,BanProgramAD,REJECT
  - RULE-SET,BanAD,REJECT
  - RULE-SET,Microsoft,Auto
  - RULE-SET,Apple,Auto
  - RULE-SET,ProxyMedia,Auto
  - RULE-SET,Telegram,Auto
  - RULE-SET,ProxyLite,Auto
  - GEOIP,CN,DIRECT
  - MATCH,Auto
tun:
  auto-detect-interface: true
  auto-route: true
  dns-hijack:
  - 114.114.114.114
  - 180.76.76.76
  - 119.29.29.29
  - 223.5.5.5
  - 8.8.8.8
  - 8.8.4.4
  - 1.1.1.1
  - 1.0.0.1
  enable: true
  stack: system