name: dnsmasq-china-list

on:
  schedule:
    - cron: '0 1 * * *' # every day at midnight

  workflow_dispatch:
    inputs:
      tags:
        description: 'Input dnsmasq-china-list tag'
        required: false
        type: string


jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Clone Current Repository
        uses: actions/checkout@v6
      
      - name: Checkout dnsmasq-china-list Code
        run: |
          git clone --depth 1 --branch main https://github.com/felixonmars/dnsmasq-china-list.git dnsconf

      - name: Build for smartDNS
        run: |
          cd dnsconf
          make SERVER=domestic SMARTDNS_SPEEDTEST_MODE=none smartdns-domain-rules
          mv accelerated-domains.china.domain.smartdns.conf google.china.domain.smartdns.conf apple.china.domain.smartdns.conf ../dnsmasq-china-list
          cd ..
          rm -rf dnsconf

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update dnsmasq-china-list
          commit_user_name: github-actions
          commit_user_email: github-actions@users.noreply.github.com
          branch: main
          file_pattern: 'dnsmasq-china-list/*'